// static-website/vue-bench/src/components/Benchmarker.vue
<script setup>
    const time = new Date();
    const requestStart = window.performance.timing.requestStart;
    const fullTime = time - requestStart;
</script>

<template>
    <div class="timer-header">Simple Vue.JS benchmark</div>
    <div class="timer">Time from the start of the request to when the page loaded: {{ fullTime }} ms</div>
</template>
<style scoped>
.timer-header {
    font-size: 48px;
    text-align: center;
    margin-bottom: 30px;
}

.timer {
    margin-left: 25px;
}
</style>

// static-website/angular-bench/src/app/benchmarker/benchmarker.component.ts
import { Component, Input } from '@angular/core';
import { Benchmarker } from '../benchmarker';

@Component({
  selector: 'app-benchmarker',
  standalone: true,
  templateUrl: './benchmarker.component.html',
  styleUrls: ['./benchmarker.component.css']
})
export class BenchmarkerComponent {
  title = 'benchmarker';
  @Input() benchmarker!: Benchmarker;
}

<div>
<div class='timer-header'>
    Simple Angular Benchmark
</div>
<div class='timer'>Time from the start of the request to when the page loaded: {{ benchmarker.timer }}  ms</div>
</div>
