// static-website/svelte-bench/src/App.svelte
<script>
	const time = new Date();
	const requestTime = window.performance.timing.requestStart;
	const fullTime = time - requestTime;
</script>

<main>
	<div class='timer-header'>
		Simple Svelte Benchmark
	</div>
	<div class='timer'>Time from the start of the request to when the page loaded: {fullTime} ms</div>
</main>

// static-website/react-bench/src/App.js
import './App.css';

function App() {
  const currentTime = new Date();
  const timer = currentTime - window.performance.timing.requestStart;

  return (
    <div className="App" >
      <div className='timer-header'>
        Simple React Benchmark
      </div>
      <div id='timer'>Time from the start of the request to when the page loaded: {timer} ms</div>
    </div>
  );
}

export default App;
