// static-website/angular-bench/src/app/app.component.ts
import { Component } from '@angular/core';
import { BenchmarkerComponent } from './benchmarker/benchmarker.component';
import { Benchmarker } from './benchmarker';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    BenchmarkerComponent,
  ],
  template: `
  <main>
  <section class="content">
    <app-benchmarker [benchmarker]="benchmarker"></app-benchmarker>
  </section>
</main>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  currentTime = new Date();
  //@ts-ignore
  timer = this.currentTime - window.performance.timing.requestStart;
  title = 'angular-bench';

  benchmarker: Benchmarker = {
    timer: this.timer
  }
}

// static-website/react-bench/src/App.js
import './App.css';

function App() {
  const currentTime = new Date();
  const timer = currentTime - window.performance.timing.requestStart;

  return (
    <div className="App" >
      <div className='timer-header'>
        Simple React Benchmark
      </div>
      <div id='timer'>Time from the start of the request to when the page loaded: {timer} ms</div>
    </div>
  );
}

export default App;
